services:
  cache:
    image: redis:7.4.1-alpine
    restart: always
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - '0.0.0.0:3089:80'
    links:
      - cache
      - selenium-hub
    depends_on:
      cache:
        condition: service_healthy
      selenium-hub:
        condition: service_started

  chrome:
    platform: linux/x86_64
    image: selenium/node-chrome:4.25.0-20241010
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    platform: linux/x86_64
    image: selenium/hub:4.25.0-20241010
    container_name: selenium-hub
    ports:
      - "127.0.0.1:4442:4442"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"